BEGIN
EXECUTE IMMEDIATE 'DROP TABLE comanda_produse CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE comenzi CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE produse CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE plati CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE soferi CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE clienti CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE restaurante CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE adrese CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE adrese (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        oras VARCHAR2(100) NOT NULL,
                        strada VARCHAR2(100) NOT NULL,
                        numar VARCHAR2(20) NOT NULL
);

CREATE TABLE clienti (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nume VARCHAR2(100) NOT NULL,
                         telefon VARCHAR2(20) NOT NULL,
                         adresa_id NUMBER NOT NULL,

                         CONSTRAINT fk_clienti_adrese
                             FOREIGN KEY (adresa_id)
                                 REFERENCES adrese(id)
                                 ON DELETE CASCADE
);

CREATE TABLE restaurante (
                             id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nume VARCHAR2(100) NOT NULL,
                             adresa_id NUMBER NOT NULL,

                             CONSTRAINT fk_restaurante_adrese
                                 FOREIGN KEY (adresa_id)
                                     REFERENCES adrese(id)
                                     ON DELETE CASCADE
);

CREATE TABLE soferi (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nume VARCHAR2(100) NOT NULL,
                        telefon VARCHAR2(20) NOT NULL,
                        salariu NUMBER(10,2) NOT NULL,
                        numar_masina VARCHAR2(30) NOT NULL,
                        disponibil NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE produse (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nume VARCHAR2(100) NOT NULL,
                         pret NUMBER(10,2) NOT NULL,
                         categorie VARCHAR2(100) NOT NULL,
                         restaurant_id NUMBER NOT NULL,

                         CONSTRAINT fk_produse_restaurante
                             FOREIGN KEY (restaurant_id)
                                 REFERENCES restaurante(id)
                                 ON DELETE CASCADE
);

CREATE TABLE plati (
                       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       suma NUMBER(10,2) NOT NULL,
                       metoda_plata VARCHAR2(50) NOT NULL,
                       efectuata NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE comenzi (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         client_id NUMBER NOT NULL,
                         restaurant_id NUMBER NOT NULL,
                         sofer_id NUMBER,
                         plata_id NUMBER,
                         status VARCHAR2(30) NOT NULL,

                         CONSTRAINT fk_comenzi_clienti
                             FOREIGN KEY (client_id)
                                 REFERENCES clienti(id)
                                 ON DELETE CASCADE,

                         CONSTRAINT fk_comenzi_restaurante
                             FOREIGN KEY (restaurant_id)
                                 REFERENCES restaurante(id)
                                 ON DELETE CASCADE,

                         CONSTRAINT fk_comenzi_soferi
                             FOREIGN KEY (sofer_id)
                                 REFERENCES soferi(id)
                                 ON DELETE SET NULL,

                         CONSTRAINT fk_comenzi_plati
                             FOREIGN KEY (plata_id)
                                 REFERENCES plati(id)
                                 ON DELETE SET NULL
);

CREATE TABLE comanda_produse (
                                 comanda_id NUMBER NOT NULL,
                                 produs_id NUMBER NOT NULL,
                                 cantitate NUMBER DEFAULT 1 NOT NULL,

                                 PRIMARY KEY (comanda_id, produs_id),

                                 CONSTRAINT fk_comanda_produse_comenzi
                                     FOREIGN KEY (comanda_id)
                                         REFERENCES comenzi(id)
                                         ON DELETE CASCADE,

                                 CONSTRAINT fk_comanda_produse_produse
                                     FOREIGN KEY (produs_id)
                                         REFERENCES produse(id)
                                         ON DELETE CASCADE
);